using Firebase.Auth;
using Firebase.Database;
using Firebase.Database.Query;
using Microsoft.Maui.ApplicationModel.Communication;

namespace Lovy.Views.Auth;

public partial class EmailPage : ContentPage
{
    FirebaseClient firebaseClient = new FirebaseClient("https://lovy-a520b-default-rtdb.firebaseio.com/");
    private FirebaseAuthProvider authProvider;
    public string webApiKey = "AIzaSyBTIQSaK_zeVVnCYTy9ShYo9QmkTAXpz4s";
    public EmailPage()
	{
		InitializeComponent();
	}
    private async void NextButton_Clicked(object sender, EventArgs e)
    {
        try
        {
            // Initialize the Firebase AuthProvider
            var authProvider = new FirebaseAuthProvider(new FirebaseConfig(webApiKey));

            var auth = await authProvider.CreateUserWithEmailAndPasswordAsync(EmailEntry.Text, PasswordEntry.Text);
            string gettoken = auth.FirebaseToken;
            //await App.Current.MainPage.DisplayAlert("Alert", gettoken, "Ok");

            // Create a new node in the database for the user
            var newUser = await firebaseClient.Child("users").PostAsync(new
            {
                Email = EmailEntry.Text,
                Password = PasswordEntry.Text,
                Token = gettoken
            });

            // Optionally, you can get the unique key generated by Firebase for the new user entry
            string userId = newUser.Key;

            await Shell.Current.GoToAsync(nameof(RulePage));
        }
        catch (Exception ex)
        {
            await App.Current.MainPage.DisplayAlert("Alert", ex.Message, "OK");
        }


    }
    private void OnImageTapped(object sender, EventArgs e)
    {
        // Handle the image tap event
        // Navigation.PopAsync(); // Go back to the previous page
        Shell.Current.GoToAsync(nameof(LoginPage));
    }
}